// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxiCompany.Domain.Context;

#nullable disable

namespace TaxiCompany.Domain.Migrations
{
    [DbContext(typeof(TaxiCompanyDbContext))]
    [Migration("20241108091532_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaxiCompany.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedDriverId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_driver_id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("colour");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<DateTime>("RealeseYear")
                        .HasMaxLength(4)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_year");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("car");
                });

            modelBuilder.Entity("TaxiCompany.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("client");
                });

            modelBuilder.Entity("TaxiCompany.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("address");

                    b.Property<int>("AssignedCarId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_car_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("full_name");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("passport");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCarId")
                        .IsUnique();

                    b.HasIndex("Passport")
                        .IsUnique();

                    b.ToTable("driver");
                });

            modelBuilder.Entity("TaxiCompany.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedCarId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_car_id");

                    b.Property<int>("AssignedClientId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_client_id");

                    b.Property<decimal>("Cost")
                        .HasMaxLength(10)
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("Date")
                        .HasMaxLength(10)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departure");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destination");

                    b.Property<TimeOnly>("DrivingTime")
                        .HasMaxLength(10)
                        .HasColumnType("time without time zone")
                        .HasColumnName("driving_time");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCarId");

                    b.HasIndex("AssignedClientId");

                    b.ToTable("trip");
                });

            modelBuilder.Entity("TaxiCompany.Domain.Entities.Driver", b =>
                {
                    b.HasOne("TaxiCompany.Domain.Entities.Car", null)
                        .WithOne()
                        .HasForeignKey("TaxiCompany.Domain.Entities.Driver", "AssignedCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxiCompany.Domain.Entities.Trip", b =>
                {
                    b.HasOne("TaxiCompany.Domain.Entities.Car", null)
                        .WithMany()
                        .HasForeignKey("AssignedCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiCompany.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("AssignedClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
